# Generated by Django 4.2.1 on 2023-05-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='code created')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.codein'),
        ),
    ]
