# Generated by Django 4.2.1 on 2023-05-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_codein_customuser_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeIn',
            new_name='ConfirmationCode',
        ),
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='code',
            new_name='_code',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='code',
            new_name='_code',
        ),
    ]
