# Generated by Django 4.2.1 on 2023-06-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='board',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
