# Generated by Django 4.2.1 on 2023-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_count_alter_board_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='board_photos'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
