# Generated by Django 4.2.1 on 2023-06-09 15:57

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_photo_alter_condition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.board_photo_upload_path),
        ),
    ]
