# Generated by Django 4.2.1 on 2023-06-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='photo',
        ),
        migrations.CreateModel(
            name='PhotoBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.board')),
            ],
        ),
    ]
