# Generated by Django 4.2.1 on 2023-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_board_photo_photoboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboard',
            name='image',
            field=models.ImageField(upload_to='board_photos/'),
        ),
    ]
