# Generated by Django 4.2.1 on 2023-06-09 17:27

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_photoboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.board_photo_upload_path),
        ),
        migrations.DeleteModel(
            name='PhotoBoard',
        ),
    ]
