# Generated by Django 4.2.1 on 2023-06-09 17:37

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_photo_delete_photoboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(null=True, upload_to=board.models.board_photo_upload_path),
        ),
    ]
