# Generated by Django 4.2.1 on 2023-06-10 15:46

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_board_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(default='board_photos/photo_default.png', null=True, upload_to=board.models.board_photo_upload_path),
        ),
    ]
