# Generated by Django 4.2.1 on 2023-06-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_board_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo_mini',
            field=models.ImageField(default='board_photos/photo_default.png', null=True, upload_to=''),
        ),
    ]
