# Generated by Django 4.2.1 on 2023-06-12 17:05

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_board_photo_mini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='photo_mini',
        ),
        migrations.AddField(
            model_name='board',
            name='photo_icon',
            field=models.ImageField(default='board_photos/photo_default_icon.png', null=True, upload_to=board.models.board_photo_icon_upload_path),
        ),
        migrations.AddField(
            model_name='board',
            name='photo_page',
            field=models.ImageField(default='board_photos/photo_default_page.png', null=True, upload_to=board.models.board_photo_page_upload_path),
        ),
    ]
