# Generated by Django 4.2.1 on 2023-07-31 14:48

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_remove_board_photo_mini_board_photo_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(default='photo_default.png', upload_to=board.models.board_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='board',
            name='photo_icon',
            field=models.ImageField(upload_to=board.models.board_photo_icon_upload_path),
        ),
        migrations.AlterField(
            model_name='board',
            name='photo_page',
            field=models.ImageField(upload_to=board.models.board_photo_page_upload_path),
        ),
    ]
